name: "tensorrt_add"
platform: "tensorrt_plan"
max_batch_size: 0

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  },
  {
    name: "INPUT1"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  }
]
